version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - aws-cli/setup
      - run: python --version
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t aws-billing-to-slack:latest .

workflows:
  main-workflow:
    jobs:
      - build:
          context:
            - aws
